### ISSUE TITLE
Password is revealed in log on failed chart download

### ISSUE THREAD

**Issue by KPilnacek** [rossumai/chart-updater#2]
Actual log: 

`2020-05-11 12:19:18,709 Cannot download chart list: 503 Server Error: Service Temporarily Unavailable for url: https://rossum:the_password@helm.private.repo/index.yaml`

Expected log:

`2020-05-11 12:19:18,709 Cannot download chart list: 503 Server Error: Service Temporarily Unavailable for url: https://rossum:[masked]@helm.private.repo/index.yaml`

**Comment by pinkavaj** [comment]
This should be closed by #11
